### ISSUE TITLE
Is source code available for the expression-evaluator

### ISSUE THREAD

**Issue by michaelthoward** [Shy-Ta/expression-evaluator-demo#1]
Q: Is source code available for the expression-evaluator library itself? 

Thanks,
Michael

**Comment by Shy-Ta** [comment]
Yes
However it is not needed for stateless functions; there's an example that demonstrates adding custom function using the library.
I am planning to soon add capabilities for stateful functions like SUM, AVG (Average). I will at that point see if the code for library itself is well documented and will upload as a separate project.
